### ISSUE TITLE
Report does not contain all user data

### ISSUE THREAD

**Issue by JonathanMayer87** [jasperbaes/Conditional-Access-Matrix#1]
The script discovers all users, but then the data on the conditional access for all users are not in the report.

![image](https://github.com/user-attachments/assets/0a2dc96c-4e25-4b31-a7ad-4093246bbb11)

In that example, the csv and json contains only 10 users.

**Comment by jasperbaes** [comment]
Hi @JonathanMayer87, thank you for reporting this issue. I’ll look into it and try to replicate the problem to find out what’s going on.

**Comment by jasperbaes** [comment]
Hi @JonathanMayer87, the issue has been resolved and a new version has been published. It turns out that the script had a development mode enabled, which only loops through the first 10 users. That line was still active, causing the report to only include data for 10 users. Please update to the latest version and let me know if you encounter any further issues. Enjoy! - Jasper

**Comment by JonathanMayer87** [comment]
Thank you very much @jasperbaes! It works well now and the tool, as well as the whole framework is super useful!
